### ISSUE TITLE
Switch to Storyboards

### ISSUE THREAD

**Issue by matthewpalmer** [matthewpalmer/Charter#1]
One of the things I noticed when watching @orta’s tvOS app code review video was how helpful it was to have a storyboard to look at when first seeing the codebase. I want new contributors to this app to be able to get a quick overview of the app flow, and a storyboard is the best way to do that. While it might not be 100% the best technical choice, the value it'll add to the community is too much to ignore.

**Comment by orta** [comment]
Given the relative size of the codebase, you could probably do a 30m video covering everything too. If you considered it a part  of lowering the barriers to contribution, then anyone who wants to start contributing seriously would be able to watch that then have an idea of where to scratch their itch.

**Comment by matthewpalmer** [comment]
Hmm that's a super interesting idea. I wonder if maybe a written document/tutorial would be easier just so that anyone can update it and we don't end up with an outdated video. Though there's definitely something to be said for having someone talk through the code. Either way you've given me a lot to think about 😀

**Comment by matthewpalmer** [comment]
Decided against this because I wanted explicit control over instantiation and presentation of view controllers
