### ISSUE TITLE
Localisation branch

### ISSUE THREAD

**Issue by franciscoamado** [matthewpalmer/Charter#36]
Hi, 
I'm sorry to bother but I took the liberty to localize your app to Portuguese and Spanish. My problem is that I created a branch for it, directly from your repository instead of forking first.
Only noticed it when was pushing the commit.

Are you interested in localizing it as you say in the Readme?
If so, any advice on how to handle it now or should I just create the PR?

**Comment by matthewpalmer** [comment]
That's amazing! 😍

I think this should work:
1. Fork this repo to your Github profile
2. In your current local clone, do `git remote add myfork https://github.com/FranciscoAmado/Charter`
3. Push your changes from local to your fork with `git push myfork branch-name`
4. Open a PR on this repo with your changes in the fork

Let me know if that doesn't work or you have any trouble with it :smile: 

Thanks again!

**Comment by franciscoamado** [comment]
Thanks for the help, solve it and opened a PR

**Comment by matthewpalmer** [comment]
Okay great, closing this :+1:
